mysql:
  image: mysql:5.7
  command: mysqld --user=root --verbose
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "test"
    MYSQL_USER: "mysql"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
